name: BetterRaw
author: Ad5001
version: "0.2"
api: 1.13.0
main: Ad5001\BetterRaw\Main
website: http://ad5001.tk

description: Custom raw messages plugin for new api
commands:
 tellraw:
  description: "§6This is a tellraw command like in PC. Display in the chat of a specific player a custom raw message"
  usage: "§a/tellraw <player> <message...>"
  permission: braw.command.tellraw
  aliases: [tr]
 sayworldraw:
  description: "§6Display in the chat of every players in a specific world a custom raw message"
  usage: "§a/sayworldraw <world> <message...>"
  permission: braw.command.sayworldraw
  aliases: [swr]
 saygmraw:
  description: "§6Display in the chat of every players in a specific gamemode a custom raw message"
  usage: "§a/saygmraw <world> <message...>"
  permission: braw.command.saygmraw
  aliases: [sgmr]
permissions:
   braw.command.tellraw:
    default: op
    description: "§6Send the player a raw message you want"
   braw.command.sayworldraw:
    default: op
    description: "§6Display in the chat of every players in a specific world a custom raw message"
   braw.command.saygmraw:
    default: op
    description: "§6Display in the chat of every players in a specific gamemode a custom raw message"
...
