name: Test
author: Ad5001
version: "0.01"
api: 1.13.0
main: Ad5001\BetterTell\Main
website: http://ad5001.tk

description: TellRaw plugin for new api
commands:
 tellraw:
  description: "ยง6This is a tellraw command like in PC.That display in the chat what do you sayed sayed"
  usage: "ยงa/tellraw <player> <text>"
  permission: btell.command.tellraw
permissions:
   btell.command.tellraw:
    default: op
    description: "ยง6Send the player the message you want"
...
