name: BetterRaw
author: Ad5001
version: "0.2"
api: 1.13.0
main: Ad5001\BetterRaw\Main
website: http://ad5001.tk

description: Custom raw messages plugin for new api
commands:
 getgm:
  description: "ยง6Get your gamemode"
  usage: "ยงa/getgm"
...
